### ISSUE TITLE
Issue with 3.1.2 android compiling

### ISSUE THREAD

**Issue by alperc84** [kestrelm/Creature_Godot#17]
Hi, new godot version arrived (3.1.2). creaturegodot3 still working with godot 3.1.2 windows target builds. But android target brings some errors. godot 3.1.1 android target still works ok, but 3.1.2.

`[Initial build] Compiling ==> modules/creaturegodot/CreatureModule.cpp
[Initial build] Compiling ==> modules/creaturegodot/MeshBone.cpp
modules/creaturegodot/CreatureModule.cpp:1496:13: error: cannot use 'throw' with
      exceptions disabled
            throw "CreatureManager::PoseCreature() - Invalid animation name!";
            ^
modules/creaturegodot/CreatureModule.cpp:1567:4: error: cannot use 'throw' with
      exceptions disabled
                        throw "CreatureManager::PoseCreature() - Invali...
                        ^
scons: building terminated because of errors.
`

I am not familliar to c++. I improvised totally and removed that conditions in CreatureModule.cpp which cause build errors:

`if (animations.count(animation_name_in) <= 0)
        {
            std::cerr<<"CreatureManager::PoseCreature() - Animation not found: "<<animation_name_in<<std::endl;
            throw "CreatureManager::PoseCreature() - Invalid animation name!";
            return;
        }`

**Now builds apk perfectly. But is that safe ?**

OS: debian-10.2.0-amd64
Godot version: 3.1.2
Steps to reproduce error: scons -j4 platform=android tools=no target=release android_arch=armv7

**Comment by kestrelm** [comment]
Hello yes it should be fine. The throw is just an added feature to allow the caller to handle any that exception if required. It is strange 3.1.2 disabled exceptions but 3.1.1 did not. Will continue to monitor it but you can remove the throw if you want.

**Comment by alperc84** [comment]
perfect thank you!
