### ISSUE TITLE
Build fails with godot 3.2

### ISSUE THREAD

**Issue by avivazran** [kestrelm/Creature_Godot#19]
Output
`$ scons platform=windows bite=64
scons: Reading SConscript files ...
Configuring for Windows: target=debug, bits=default
Found MSVC version 14.2, arch amd64, bits=64
Checking for C header file mntent.h... (cached) no
scons: done reading SConscript files.
scons: Building targets ...
Compiling ==> modules\creaturegodot\creaturegodot.cpp
creaturegodot.cpp
modules\creaturegodot\creaturegodot.cpp(456): error C2653: 'VS': is not a class or namespace name
modules\creaturegodot\creaturegodot.cpp(456): error C3861: 'get_singleton': identifier not found
modules\creaturegodot\creaturegodot.cpp(831): error C2039: 'REAL': is not a member of 'Variant'
D:\Software\Godot\godot\core/variant.h(77): note: see declaration of 'Variant'
modules\creaturegodot\creaturegodot.cpp(831): error C2065: 'REAL': undeclared identifier
modules\creaturegodot\creaturegodot.cpp(831): error C2660: 'ClassDB::add_property': function does not take 3 arguments
D:\Software\Godot\godot\core/class_db.h(353): note: see declaration of 'ClassDB::add_property'
modules\creaturegodot\creaturegodot.cpp(832): error C2039: 'REAL': is not a member of 'Variant'
D:\Software\Godot\godot\core/variant.h(77): note: see declaration of 'Variant'
modules\creaturegodot\creaturegodot.cpp(832): error C2065: 'REAL': undeclared identifier
modules\creaturegodot\creaturegodot.cpp(832): error C2660: 'ClassDB::add_property': function does not take 3 arguments
D:\Software\Godot\godot\core/class_db.h(353): note: see declaration of 'ClassDB::add_property'
scons: *** [modules\creaturegodot\creaturegodot.windows.tools.64.obj] Error 2
scons: building terminated because of errors.
`

**Comment by kestrelm** [comment]
Hello,
I just checked out the: Godot Engine v3.2.1.stable and built everything from scratch with no errors. Will investigate more but the plugin seems to be building fine on v3.2.1.

Thanks

**Comment by alperc84** [comment]
I can confirm 3.2.1-stable built **without any problems** on me too. I am building in ubuntu 18.0.4 for linux + windows + android. Never tried for ios or mac btw.

**Comment by avivazran** [comment]
the official github repo seems to contain source code only for godot3.2, while the official site provides a zipped installer for versions 3.2.1 and 3.2.2 but not the source code itself for those versions.
can someone please provide a download link  for the src codes?

**Comment by kestrelm** [comment]
Just check out the git repository from Godot and set your branch to 3.2.1.

Thanks

**Comment by avivazran** [comment]
Confirmed successful build with godot 3.2.1 windows 64 bit.
thank you!
